version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-reader
    environment:
      POSTGRES_DB: read_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - readData:/var/lib/postgresql/data

volumes:
  readData: